/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package princewheel;

import java.sql.*;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author owner
 */
public class AdminHome extends javax.swing.JFrame {

    /**
     * Creates new form AdminHome
     */
    
    // database declaration
    Statement st;
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    
    String username = "root";
    String password = "";
    String url = "jdbc:mysql://localhost:3306/princewheeldb";
    
    
    public AdminHome() {
        initComponents();
        hidecomponets();
        loadiconsimages();
        carreporttable();
        staffreporttable();
    }
   final void hidecomponets(){
    jpstaffaccount.setVisible(false);
    jpaddcar.setVisible(false);
    jpcarpricing.setVisible(false);
    jpaddstaff.setVisible(false);
    jporgreport.setVisible(false);
    jpstaffreport.setVisible(false);
    jpcarreports.setVisible(false);
    }
  final void loadiconsimages(){
   ImageIcon  serch,upda,del,ad,hod;
   serch  = new ImageIcon("images/search.png");
   upda  = new ImageIcon("images/update.png");
   del  = new ImageIcon("images/delete.png");
   ad  = new ImageIcon("images/add.png");
   hod  = new ImageIcon("images/hold.png");
   btnsearch.setIcon(serch);
   btnsearchreport.setIcon(serch);
   btnsearchstaffreport.setIcon(serch);
   btnsearchaddcar.setIcon(serch);
   btnaddcar.setIcon(ad);
   btnupdatecar.setIcon(upda);
   btndeletecar.setIcon(del);
   btnholdcar.setIcon(hod);
   }
  final void  carreporttable(){
  DefaultTableModel dtm = new DefaultTableModel();
  dtm.addColumn("Car No");
  dtm.addColumn("Car Type");
  dtm.addColumn("Car Status");
  dtm.addColumn("Ins Expiry");
  dtm.addColumn("Avilability");
  dtm.addColumn("Car Class");
  dtm.addColumn("Lease Price");
  dtm.addColumn("Discount");
   tblcarreport.setModel(dtm);
  }
  final void staffreporttable(){
   DefaultTableModel dtm = new DefaultTableModel();
  dtm.addColumn("E-Code ");
  dtm.addColumn("Category");
  dtm.addColumn("Acc Status");
  dtm.addColumn("Age");
  dtm.addColumn("Avilability");
  dtm.addColumn("Enroll");
  dtm.addColumn("Asigns");
   tblstaffreport.setModel(dtm);
  }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jpstaffaccount = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        btnsearch = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jpcarpricing = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        cmbtype = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lbtype = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbdiscount = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lbcoution = new javax.swing.JLabel();
        lbprice = new javax.swing.JLabel();
        jpaddcar = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtcarcapacity = new javax.swing.JTextField();
        txtcarprimeyears = new javax.swing.JTextField();
        txtinsurancecompany = new javax.swing.JTextField();
        txtcarno = new javax.swing.JTextField();
        cmbbranch = new javax.swing.JComboBox<>();
        cmbcartype = new javax.swing.JComboBox<>();
        cmbclass = new javax.swing.JComboBox<>();
        jdstatinsurance = new com.toedter.calendar.JDateChooser();
        jdendinsurance = new com.toedter.calendar.JDateChooser();
        jdbought = new com.toedter.calendar.JDateChooser();
        cmbcarstatus = new javax.swing.JComboBox<>();
        btnsearchaddcar = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        btnholdcar = new javax.swing.JButton();
        btndeletecar = new javax.swing.JButton();
        btnupdatecar = new javax.swing.JButton();
        btnaddcar = new javax.swing.JButton();
        jpaddstaff = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jTextField18 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        cmbcounties = new javax.swing.JComboBox<>();
        jComboBox5 = new javax.swing.JComboBox<>();
        jComboBox6 = new javax.swing.JComboBox<>();
        jComboBox7 = new javax.swing.JComboBox<>();
        jTextField19 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jDateChooser4 = new com.toedter.calendar.JDateChooser();
        jButton11 = new javax.swing.JButton();
        jLabel36 = new javax.swing.JLabel();
        jTextField22 = new javax.swing.JTextField();
        jpcarreports = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblcarreport = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        txtcarnoreport = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        btnsearchreport = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        cmbcartypereport = new javax.swing.JComboBox<>();
        jButton12 = new javax.swing.JButton();
        jpstaffreport = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jTextField23 = new javax.swing.JTextField();
        jComboBox4 = new javax.swing.JComboBox<>();
        btnsearchstaffreport = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblstaffreport = new javax.swing.JTable();
        jporgreport = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmaddcar = new javax.swing.JMenuItem();
        jmcarpricing = new javax.swing.JMenuItem();
        jmdailyrequest = new javax.swing.JMenuItem();
        jmlogout = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmcarreport = new javax.swing.JMenuItem();
        jmorgreport = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jmstaffreport = new javax.swing.JMenuItem();
        jmaddstaff = new javax.swing.JMenuItem();
        jmstaffaccount = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(1132, 537));
        jPanel1.setLayout(null);

        jpstaffaccount.setBackground(new java.awt.Color(255, 255, 255));
        jpstaffaccount.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Staff Accounts", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Wide Latin", 0, 12))); // NOI18N
        jpstaffaccount.setLayout(null);

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel4.setLayout(null);

        jLabel6.setText("E-Code :");
        jPanel4.add(jLabel6);
        jLabel6.setBounds(10, 20, 60, 14);
        jPanel4.add(jTextField4);
        jTextField4.setBounds(90, 20, 120, 20);

        jLabel8.setText("E-Name :");
        jPanel4.add(jLabel8);
        jLabel8.setBounds(10, 60, 60, 14);
        jPanel4.add(jTextField5);
        jTextField5.setBounds(90, 90, 120, 20);
        jPanel4.add(jTextField6);
        jTextField6.setBounds(90, 60, 120, 20);
        jPanel4.add(jTextField7);
        jTextField7.setBounds(230, 60, 120, 20);

        jLabel11.setText("E-occupation :");
        jPanel4.add(jLabel11);
        jLabel11.setBounds(10, 130, 80, 14);
        jPanel4.add(jTextField8);
        jTextField8.setBounds(90, 130, 120, 20);

        jLabel12.setText("E-Status :");
        jPanel4.add(jLabel12);
        jLabel12.setBounds(270, 90, 60, 14);
        jPanel4.add(jTextField9);
        jTextField9.setBounds(240, 110, 100, 20);

        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });
        jPanel4.add(btnsearch);
        btnsearch.setBounds(230, 13, 40, 40);

        jpstaffaccount.add(jPanel4);
        jPanel4.setBounds(6, 26, 360, 170);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.setLayout(null);

        jButton3.setBackground(new java.awt.Color(123, 193, 249));
        jButton3.setFont(new java.awt.Font("Wide Latin", 0, 10)); // NOI18N
        jButton3.setText("Release account");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton3);
        jButton3.setBounds(10, 80, 170, 50);

        jButton4.setBackground(new java.awt.Color(123, 193, 249));
        jButton4.setFont(new java.awt.Font("Wide Latin", 0, 10)); // NOI18N
        jButton4.setText("Frizee account");
        jPanel5.add(jButton4);
        jButton4.setBounds(10, 10, 160, 50);

        jButton5.setBackground(new java.awt.Color(123, 193, 249));
        jButton5.setFont(new java.awt.Font("Wide Latin", 0, 10)); // NOI18N
        jButton5.setText("Hold account");
        jPanel5.add(jButton5);
        jButton5.setBounds(180, 10, 160, 50);

        jButton6.setBackground(new java.awt.Color(123, 193, 249));
        jButton6.setFont(new java.awt.Font("Wide Latin", 0, 10)); // NOI18N
        jButton6.setText("Delete ");
        jPanel5.add(jButton6);
        jButton6.setBounds(190, 80, 150, 50);

        jpstaffaccount.add(jPanel5);
        jPanel5.setBounds(10, 210, 360, 150);

        jPanel1.add(jpstaffaccount);
        jpstaffaccount.setBounds(370, 80, 390, 380);

        jpcarpricing.setBackground(new java.awt.Color(255, 255, 255));
        jpcarpricing.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Car pricing", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Wide Latin", 0, 12))); // NOI18N
        jpcarpricing.setLayout(null);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "New Price", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Wide Latin", 0, 11))); // NOI18N
        jPanel2.setLayout(null);

        jLabel1.setText("CAR TYPE :");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(10, 50, 60, 14);

        jLabel2.setText("COUTION :");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(10, 80, 54, 14);

        jLabel3.setText("LEASE PRICE :");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(10, 110, 70, 14);

        jLabel4.setText("DISCOUNT :");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(10, 150, 70, 14);

        jButton1.setBackground(new java.awt.Color(123, 193, 249));
        jButton1.setFont(new java.awt.Font("Wide Latin", 0, 11)); // NOI18N
        jButton1.setText("SAVE");
        jPanel2.add(jButton1);
        jButton1.setBounds(10, 281, 110, 40);

        jButton2.setBackground(new java.awt.Color(123, 193, 249));
        jButton2.setFont(new java.awt.Font("Wide Latin", 0, 11)); // NOI18N
        jButton2.setText("UPDATE");
        jPanel2.add(jButton2);
        jButton2.setBounds(130, 281, 130, 40);

        cmbtype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbtype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbtypeActionPerformed(evt);
            }
        });
        jPanel2.add(cmbtype);
        cmbtype.setBounds(110, 50, 130, 20);
        jPanel2.add(jTextField1);
        jTextField1.setBounds(110, 80, 130, 20);
        jPanel2.add(jTextField2);
        jTextField2.setBounds(110, 110, 130, 20);
        jPanel2.add(jTextField3);
        jTextField3.setBounds(110, 140, 130, 20);

        jpcarpricing.add(jPanel2);
        jPanel2.setBounds(6, 26, 280, 340);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Current Price", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Wide Latin", 0, 11))); // NOI18N
        jPanel3.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Wide Latin", 2, 11)); // NOI18N
        jLabel5.setText("CAR TYPE  :");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(20, 40, 130, 12);

        lbtype.setText("Type");
        jPanel3.add(lbtype);
        lbtype.setBounds(30, 70, 80, 14);

        jLabel7.setFont(new java.awt.Font("Wide Latin", 2, 11)); // NOI18N
        jLabel7.setText(" PRICE :");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(30, 110, 100, 12);

        lbdiscount.setText("Ksh .");
        jPanel3.add(lbdiscount);
        lbdiscount.setBounds(30, 210, 90, 14);

        jLabel9.setFont(new java.awt.Font("Wide Latin", 2, 11)); // NOI18N
        jLabel9.setText("DISCOUNT :");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(20, 180, 130, 12);

        jLabel10.setFont(new java.awt.Font("Wide Latin", 2, 11)); // NOI18N
        jLabel10.setText("COUTION :");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(20, 240, 120, 12);

        lbcoution.setText("Ksh .");
        jPanel3.add(lbcoution);
        lbcoution.setBounds(30, 270, 100, 14);

        lbprice.setText("Ksh .");
        jPanel3.add(lbprice);
        lbprice.setBounds(30, 140, 80, 14);

        jpcarpricing.add(jPanel3);
        jPanel3.setBounds(300, 30, 180, 330);

        jPanel1.add(jpcarpricing);
        jpcarpricing.setBounds(310, 80, 510, 380);

        jpaddcar.setBackground(new java.awt.Color(255, 255, 255));
        jpaddcar.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Add Car", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Wide Latin", 0, 14))); // NOI18N
        jpaddcar.setLayout(null);

        jPanel6.setLayout(null);

        jLabel13.setText("Car Class  :");
        jPanel6.add(jLabel13);
        jLabel13.setBounds(350, 240, 110, 14);

        jLabel14.setText("Status :");
        jPanel6.add(jLabel14);
        jLabel14.setBounds(10, 110, 60, 14);

        jLabel15.setText("Capasity :");
        jPanel6.add(jLabel15);
        jLabel15.setBounds(10, 160, 60, 14);

        jLabel16.setText("Prime Years :");
        jPanel6.add(jLabel16);
        jLabel16.setBounds(10, 200, 80, 14);

        jLabel17.setText("Date Bought :");
        jPanel6.add(jLabel17);
        jLabel17.setBounds(10, 240, 80, 14);

        jLabel18.setText("Insurance Company:");
        jPanel6.add(jLabel18);
        jLabel18.setBounds(350, 40, 140, 14);

        jLabel19.setText("Insurance Date :");
        jPanel6.add(jLabel19);
        jLabel19.setBounds(350, 90, 120, 14);

        jLabel20.setText("Insurance Expiry :");
        jPanel6.add(jLabel20);
        jLabel20.setBounds(350, 130, 130, 14);

        jLabel21.setText("Allocated Banch :");
        jPanel6.add(jLabel21);
        jLabel21.setBounds(350, 200, 140, 14);

        jLabel22.setText("Car Type :");
        jPanel6.add(jLabel22);
        jLabel22.setBounds(10, 29, 60, 14);

        jLabel23.setText("Car Number :");
        jPanel6.add(jLabel23);
        jLabel23.setBounds(10, 70, 90, 14);
        jPanel6.add(txtcarcapacity);
        txtcarcapacity.setBounds(110, 160, 170, 20);
        jPanel6.add(txtcarprimeyears);
        txtcarprimeyears.setBounds(110, 200, 170, 20);
        jPanel6.add(txtinsurancecompany);
        txtinsurancecompany.setBounds(500, 40, 190, 20);
        jPanel6.add(txtcarno);
        txtcarno.setBounds(110, 70, 110, 20);

        cmbbranch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Branch A", "Branch B", "Branch C" }));
        jPanel6.add(cmbbranch);
        cmbbranch.setBounds(500, 200, 140, 20);

        cmbcartype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "X-TRAIL", "MERCEDES", "PREMIO", "PRADO", "RANGE", "PROBOX", "T WAGON", "RAV4", "LIMO", " " }));
        jPanel6.add(cmbcartype);
        cmbcartype.setBounds(110, 30, 170, 20);

        cmbclass.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Economy", "Pride", "Laxury" }));
        jPanel6.add(cmbclass);
        cmbclass.setBounds(500, 240, 140, 20);

        jdstatinsurance.setDateFormatString("dd-MM-yyyy");
        jPanel6.add(jdstatinsurance);
        jdstatinsurance.setBounds(500, 80, 170, 20);

        jdendinsurance.setDateFormatString("dd-MM-yyyy");
        jPanel6.add(jdendinsurance);
        jdendinsurance.setBounds(500, 130, 170, 20);

        jdbought.setDateFormatString("dd-MM-yyyy");
        jPanel6.add(jdbought);
        jdbought.setBounds(110, 240, 170, 20);

        cmbcarstatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active", "Hold", "Repare", "Broke down" }));
        jPanel6.add(cmbcarstatus);
        cmbcarstatus.setBounds(110, 110, 170, 20);

        btnsearchaddcar.setBackground(new java.awt.Color(123, 193, 249));
        btnsearchaddcar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchaddcarActionPerformed(evt);
            }
        });
        jPanel6.add(btnsearchaddcar);
        btnsearchaddcar.setBounds(230, 53, 50, 50);

        jpaddcar.add(jPanel6);
        jPanel6.setBounds(10, 30, 720, 310);

        jPanel7.setLayout(null);

        btnholdcar.setBackground(new java.awt.Color(123, 193, 249));
        btnholdcar.setFont(new java.awt.Font("Wide Latin", 0, 12)); // NOI18N
        btnholdcar.setText("Hold");
        jPanel7.add(btnholdcar);
        btnholdcar.setBounds(360, 10, 150, 50);

        btndeletecar.setBackground(new java.awt.Color(123, 193, 249));
        btndeletecar.setFont(new java.awt.Font("Wide Latin", 0, 12)); // NOI18N
        btndeletecar.setText("Delete");
        btndeletecar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeletecarActionPerformed(evt);
            }
        });
        jPanel7.add(btndeletecar);
        btndeletecar.setBounds(523, 10, 150, 50);

        btnupdatecar.setBackground(new java.awt.Color(123, 193, 249));
        btnupdatecar.setFont(new java.awt.Font("Wide Latin", 0, 12)); // NOI18N
        btnupdatecar.setText("Update ");
        btnupdatecar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdatecarActionPerformed(evt);
            }
        });
        jPanel7.add(btnupdatecar);
        btnupdatecar.setBounds(190, 10, 160, 50);

        btnaddcar.setBackground(new java.awt.Color(123, 193, 249));
        btnaddcar.setFont(new java.awt.Font("Wide Latin", 0, 12)); // NOI18N
        btnaddcar.setText("Add Car");
        btnaddcar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddcarActionPerformed(evt);
            }
        });
        jPanel7.add(btnaddcar);
        btnaddcar.setBounds(10, 10, 170, 50);

        jpaddcar.add(jPanel7);
        jPanel7.setBounds(10, 350, 720, 70);

        jPanel1.add(jpaddcar);
        jpaddcar.setBounds(200, 80, 750, 430);

        jpaddstaff.setBackground(new java.awt.Color(255, 255, 255));
        jpaddstaff.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Add Staff", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Wide Latin", 0, 12))); // NOI18N
        jpaddstaff.setLayout(null);

        jPanel10.setLayout(null);

        jLabel26.setText("Full Name  :");
        jPanel10.add(jLabel26);
        jLabel26.setBounds(20, 40, 70, 14);
        jPanel10.add(jTextField10);
        jTextField10.setBounds(270, 40, 160, 20);
        jPanel10.add(jTextField15);
        jTextField15.setBounds(450, 40, 160, 20);
        jPanel10.add(jTextField17);
        jTextField17.setBounds(510, 130, 160, 20);

        jLabel27.setText("ID Number :");
        jPanel10.add(jLabel27);
        jLabel27.setBounds(20, 90, 80, 14);
        jPanel10.add(jTextField18);
        jTextField18.setBounds(90, 40, 160, 20);

        jLabel28.setText("Phone :");
        jPanel10.add(jLabel28);
        jLabel28.setBounds(20, 140, 37, 14);

        jLabel29.setText("Email :");
        jPanel10.add(jLabel29);
        jLabel29.setBounds(20, 180, 31, 14);

        jLabel30.setText("Location :");
        jPanel10.add(jLabel30);
        jLabel30.setBounds(20, 220, 50, 14);

        jLabel31.setText("Year Of Birth :");
        jPanel10.add(jLabel31);
        jLabel31.setBounds(20, 260, 69, 14);

        jLabel32.setText("Gender :");
        jPanel10.add(jLabel32);
        jLabel32.setBounds(280, 90, 60, 14);

        jLabel33.setText("Branch :");
        jPanel10.add(jLabel33);
        jLabel33.setBounds(430, 200, 40, 14);

        jLabel34.setText("E-code :");
        jPanel10.add(jLabel34);
        jLabel34.setBounds(430, 160, 40, 14);

        jLabel35.setText("Assign :");
        jPanel10.add(jLabel35);
        jLabel35.setBounds(430, 250, 38, 14);

        cmbcounties.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NAIROBI", "MOMBASA", "KWALE", "KILIFI", "TANA RIVER", "LAMU", "TAITA TAVETA", "GARISSA", "WAJIR", "MANDERA", "MARSABIT", "ISIOLO", "MERU", "THARAKANITHI", "EMBU", "KITUI", "MACHAKOS", "MAKUENI", "NYANDARUS", "NYERI", "KIRINYAGA", "MURANGA", "KIAMBU", "TURKANA", "WEST POKOT", "SAMBURU", "TRANS NZOIA", "UASIN GISHU", "ELGEYO MARAKET", "NANDI", "BARINGO", "LAIKIPIA", "NAKURU", "NAROK", "KAJIADO", "BOMET", "KAKAMEGA", "VIHIGA", "BUNGOMA", "BUSIA", "SIAYA", "KISUMU", "HOMA BAY", "MIGORI", "KISII", "NYAMIRA", "KERICHO" }));
        cmbcounties.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbcountiesActionPerformed(evt);
            }
        });
        jPanel10.add(cmbcounties);
        cmbcounties.setBounds(90, 210, 160, 20);

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MALE", "FEMALE" }));
        jPanel10.add(jComboBox5);
        jComboBox5.setBounds(350, 90, 140, 20);

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MAIN BANCH", "BRANCH A", "BRANCH B" }));
        jPanel10.add(jComboBox6);
        jComboBox6.setBounds(510, 200, 160, 20);

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AGENT", "HEAD AGENT", "ENGINEER", "HEAD ENGINEER" }));
        jPanel10.add(jComboBox7);
        jComboBox7.setBounds(510, 250, 160, 20);
        jPanel10.add(jTextField19);
        jTextField19.setBounds(90, 130, 160, 20);
        jPanel10.add(jTextField20);
        jTextField20.setBounds(90, 170, 160, 20);
        jPanel10.add(jTextField21);
        jTextField21.setBounds(90, 90, 160, 20);

        jDateChooser4.setDateFormatString("dd-MM-yyyy");
        jPanel10.add(jDateChooser4);
        jDateChooser4.setBounds(100, 260, 210, 20);

        jButton11.setFont(new java.awt.Font("Wide Latin", 0, 12)); // NOI18N
        jButton11.setText("Create  New Account");
        jPanel10.add(jButton11);
        jButton11.setBounds(260, 313, 350, 40);

        jLabel36.setText("A-code :");
        jPanel10.add(jLabel36);
        jLabel36.setBounds(430, 130, 41, 14);
        jPanel10.add(jTextField22);
        jTextField22.setBounds(510, 160, 160, 20);

        jpaddstaff.add(jPanel10);
        jPanel10.setBounds(10, 30, 840, 370);

        jPanel1.add(jpaddstaff);
        jpaddstaff.setBounds(140, 80, 870, 430);

        jpcarreports.setBackground(new java.awt.Color(255, 255, 255));
        jpcarreports.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Car Reports", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Wide Latin", 0, 12))); // NOI18N
        jpcarreports.setLayout(null);

        jPanel8.setLayout(null);

        tblcarreport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblcarreport.setToolTipText("General Car Reports");
        tblcarreport.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane1.setViewportView(tblcarreport);

        jPanel8.add(jScrollPane1);
        jScrollPane1.setBounds(10, 10, 890, 260);

        jpcarreports.add(jPanel8);
        jPanel8.setBounds(10, 130, 910, 280);

        jPanel9.setLayout(null);
        jPanel9.add(txtcarnoreport);
        txtcarnoreport.setBounds(70, 10, 110, 20);

        jLabel24.setText("Car No:");
        jPanel9.add(jLabel24);
        jLabel24.setBounds(10, 10, 50, 14);

        btnsearchreport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchreportActionPerformed(evt);
            }
        });
        jPanel9.add(btnsearchreport);
        btnsearchreport.setBounds(190, 10, 50, 50);

        jLabel25.setText("Car Type :");
        jPanel9.add(jLabel25);
        jLabel25.setBounds(10, 40, 60, 14);

        cmbcartypereport.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel9.add(cmbcartypereport);
        cmbcartypereport.setBounds(70, 40, 110, 20);

        jButton12.setText("PRINT");
        jPanel9.add(jButton12);
        jButton12.setBounds(569, 43, 130, 30);

        jpcarreports.add(jPanel9);
        jPanel9.setBounds(90, 30, 720, 80);

        jPanel1.add(jpcarreports);
        jpcarreports.setBounds(90, 80, 940, 430);

        jpstaffreport.setBackground(new java.awt.Color(255, 255, 255));
        jpstaffreport.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Staff Reports", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Wide Latin", 0, 12))); // NOI18N
        jpstaffreport.setLayout(null);

        jPanel11.setLayout(null);

        jLabel37.setText("E-Code :");
        jPanel11.add(jLabel37);
        jLabel37.setBounds(28, 11, 60, 14);

        jLabel38.setText("Category :");
        jPanel11.add(jLabel38);
        jLabel38.setBounds(20, 40, 70, 14);
        jPanel11.add(jTextField23);
        jTextField23.setBounds(120, 10, 130, 20);

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel11.add(jComboBox4);
        jComboBox4.setBounds(120, 40, 130, 20);
        jPanel11.add(btnsearchstaffreport);
        btnsearchstaffreport.setBounds(260, 10, 50, 50);

        jButton14.setText("PRINT");
        jPanel11.add(jButton14);
        jButton14.setBounds(619, 23, 140, 40);

        jpstaffreport.add(jPanel11);
        jPanel11.setBounds(90, 40, 770, 70);

        jPanel12.setLayout(null);

        tblstaffreport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblstaffreport);

        jPanel12.add(jScrollPane2);
        jScrollPane2.setBounds(10, 10, 960, 260);

        jpstaffreport.add(jPanel12);
        jPanel12.setBounds(10, 130, 980, 280);

        jPanel1.add(jpstaffreport);
        jpstaffreport.setBounds(40, 80, 1010, 430);

        jporgreport.setBackground(new java.awt.Color(255, 255, 255));
        jporgreport.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Organization Reports", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Wide Latin", 0, 12))); // NOI18N

        javax.swing.GroupLayout jporgreportLayout = new javax.swing.GroupLayout(jporgreport);
        jporgreport.setLayout(jporgreportLayout);
        jporgreportLayout.setHorizontalGroup(
            jporgreportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1068, Short.MAX_VALUE)
        );
        jporgreportLayout.setVerticalGroup(
            jporgreportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 409, Short.MAX_VALUE)
        );

        jPanel1.add(jporgreport);
        jporgreport.setBounds(30, 80, 1080, 430);

        jMenu1.setText("Activity");

        jmaddcar.setText("Add Car");
        jmaddcar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmaddcarActionPerformed(evt);
            }
        });
        jMenu1.add(jmaddcar);

        jmcarpricing.setText("Car Priicing");
        jmcarpricing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmcarpricingActionPerformed(evt);
            }
        });
        jMenu1.add(jmcarpricing);

        jmdailyrequest.setText("Daily Request");
        jMenu1.add(jmdailyrequest);

        jmlogout.setText("Logout");
        jmlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmlogoutActionPerformed(evt);
            }
        });
        jMenu1.add(jmlogout);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Reports");

        jmcarreport.setText("Car Reports");
        jmcarreport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmcarreportActionPerformed(evt);
            }
        });
        jMenu2.add(jmcarreport);

        jmorgreport.setText("Org Report");
        jmorgreport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmorgreportActionPerformed(evt);
            }
        });
        jMenu2.add(jmorgreport);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Staff");

        jmstaffreport.setText("Staff Reports");
        jmstaffreport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmstaffreportActionPerformed(evt);
            }
        });
        jMenu3.add(jmstaffreport);

        jmaddstaff.setText("Add Staff");
        jmaddstaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmaddstaffActionPerformed(evt);
            }
        });
        jMenu3.add(jmaddstaff);

        jmstaffaccount.setText("Staff Accounts");
        jmstaffaccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmstaffaccountActionPerformed(evt);
            }
        });
        jMenu3.add(jmstaffaccount);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1151, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jmlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmlogoutActionPerformed
        // TODO add your handling code here:
        int action = JOptionPane.showConfirmDialog(null, "Are you sure to exit ?","PRINCE WHEEL",JOptionPane.YES_NO_OPTION);
        switch (action) {
            case JOptionPane.YES_OPTION:
                this.dispose();
                new Loader().setVisible(true);
                break;
            case JOptionPane.NO_OPTION:
                JOptionPane.showMessageDialog(null,"Still loged in ","PRINCE WHEEL",JOptionPane.INFORMATION_MESSAGE);
                break;
            default:
                JOptionPane.showMessageDialog(null,"Error occoured contact admin ","PRINCE WHEEL",JOptionPane.ERROR);
                break;
        }
    }//GEN-LAST:event_jmlogoutActionPerformed

    private void jmaddcarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmaddcarActionPerformed
        // TODO add your handling code here:
    jpstaffaccount.setVisible(false);
    
    jpcarpricing.setVisible(false);
    jpaddstaff.setVisible(false);
    jporgreport.setVisible(false);
    jpstaffreport.setVisible(false);
    jpcarreports.setVisible(false);
    jpaddcar.setVisible(true);
    }//GEN-LAST:event_jmaddcarActionPerformed

    private void jmcarpricingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmcarpricingActionPerformed
        // TODO add your handling code here:
          jpstaffaccount.setVisible(false);
    jpaddstaff.setVisible(false);
    jporgreport.setVisible(false);
    jpstaffreport.setVisible(false);
    jpcarreports.setVisible(false);
    jpaddcar.setVisible(false);
    jpcarpricing.setVisible(true);
    }//GEN-LAST:event_jmcarpricingActionPerformed

    private void jmaddstaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmaddstaffActionPerformed
        // TODO add your handling code here:
         jpstaffaccount.setVisible(false);
    
    jporgreport.setVisible(false);
    jpstaffreport.setVisible(false);
    jpcarreports.setVisible(false);
    jpaddcar.setVisible(false);
    jpcarpricing.setVisible(false);
    jpaddstaff.setVisible(true);
    }//GEN-LAST:event_jmaddstaffActionPerformed

    private void jmcarreportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmcarreportActionPerformed
        // TODO add your handling code here:
          jpstaffaccount.setVisible(false);
    jpaddstaff.setVisible(false);
    jporgreport.setVisible(false);
    jpstaffreport.setVisible(false);
    jpaddcar.setVisible(false);
    jpcarpricing.setVisible(false);
    jpcarreports.setVisible(true);
    }//GEN-LAST:event_jmcarreportActionPerformed

    private void jmorgreportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmorgreportActionPerformed
        // TODO add your handling code here:
            jpstaffaccount.setVisible(false);
    jpaddstaff.setVisible(false);
    jpstaffreport.setVisible(false);
    jpaddcar.setVisible(false);
    jpcarpricing.setVisible(false);
    jpcarreports.setVisible(false);
    jporgreport.setVisible(true);
    }//GEN-LAST:event_jmorgreportActionPerformed

    private void jmstaffreportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmstaffreportActionPerformed
        // TODO add your handling code here:
              jpstaffaccount.setVisible(false);
    jpaddstaff.setVisible(false);  
    jpaddcar.setVisible(false);
    jpcarpricing.setVisible(false);
    jpcarreports.setVisible(false);
    jporgreport.setVisible(false);
    jpstaffreport.setVisible(true);
    }//GEN-LAST:event_jmstaffreportActionPerformed

    private void jmstaffaccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmstaffaccountActionPerformed
        // TODO add your handling code here:
              
    jpaddstaff.setVisible(false);  
    jpaddcar.setVisible(false);
    jpcarpricing.setVisible(false);
    jpcarreports.setVisible(false);
    jporgreport.setVisible(false);
    jpstaffreport.setVisible(false);
    jpstaffaccount.setVisible(true);
    }//GEN-LAST:event_jmstaffaccountActionPerformed

    private void cmbtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbtypeActionPerformed
        // TODO add your handling code here:
        int selecteditem = cmbtype.getSelectedIndex();
        if(selecteditem == 0){
            String type = cmbtype.getItemAt(0);
        lbtype.setText(type);
        
        }else if(selecteditem == 1){
         String type = cmbtype.getItemAt(1);
        lbtype.setText(type);
        }
        else if(selecteditem == 2){
         String type = cmbtype.getItemAt(2);
        lbtype.setText(type);
        }
        else if(selecteditem == 3){
         String type = cmbtype.getItemAt(3);
        lbtype.setText(type);
        }
        
        else{
        JOptionPane.showMessageDialog(null, "error");
        }
    }//GEN-LAST:event_cmbtypeActionPerformed

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsearchActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnsearchreportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchreportActionPerformed
        // TODO add your handling code here:
        if("".equals(txtcarnoreport.getText())){
        JOptionPane.showMessageDialog(null,"looking for combobox");
        String cartype = cmbcartypereport.getSelectedItem().toString();
        JOptionPane.showMessageDialog(null,"looking for " + cartype);
        
        }else{
           JOptionPane.showMessageDialog(null,"looking for textbox"); 
           String carno = txtcarnoreport.getText();
           JOptionPane.showMessageDialog(null,"looking for " + carno);
        }
    }//GEN-LAST:event_btnsearchreportActionPerformed

    private void cmbcountiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbcountiesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbcountiesActionPerformed

    private void btnaddcarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddcarActionPerformed
    
        // validate inputs
        
        if(!"".equals(txtcarno.getText()) && !"".equals(txtcarprimeyears.getText()) && !"".equals(txtcarcapacity.getText()) 
                && !"".equals(txtinsurancecompany.getText())){
        try {
            validate();
            // try insert data to the database
            java.util.Date dbought,insstart,insend;
            java.sql.Date datecarbougt,insuranceend,insurancestart;
            dbought =  jdbought.getDate();
            insstart =  jdstatinsurance.getDate();
            insend =  jdendinsurance.getDate();
            datecarbougt = new java.sql.Date(dbought.getTime());
            insurancestart = new java.sql.Date(insstart.getTime());
            insuranceend = new java.sql.Date(insend.getTime());

            con = DriverManager.getConnection(url,username,password);
            st = con.createStatement();
            String sqladdcar = "INSERT INTO tbladmincar(CARTYPE,CARNO,DATEBOUGHT,CURRENTSTATUS,PRIMEYEARS,CAPACITY,INSURENCECOMPANY,"
                    + "INSURENCASTART,INSURENCEEND,CARCLASS,BRANCH) VALUES ('"+cmbcartype.getSelectedItem()+"','"+txtcarno.getText()+"'"
                    + ",'"+datecarbougt+"','"+cmbcarstatus.getSelectedItem()+"','"+txtcarprimeyears.getText()+"','"+txtcarcapacity.getText()+"'"
                    + ",'"+txtinsurancecompany.getText()+"','"+insurancestart+"','"+insuranceend+"','"+cmbclass.getSelectedItem()+"'"
                    + ",'"+cmbbranch.getSelectedItem()+"')";
            st.execute(sqladdcar);
            JOptionPane.showMessageDialog(null, "<HTML><i style=\"color: green; font-size: 12px;\">New Car Added</i></HTML>","PRINCE WHEEL",JOptionPane.INFORMATION_MESSAGE);
                    txtcarno.setText("");
                    txtcarprimeyears.setText("");
                    txtcarcapacity.setText("");
                    txtinsurancecompany.setText("");
                    jdbought.setDate(null);
                    jdstatinsurance.setDate(null);
                    jdendinsurance.setDate(null);
                    
        } catch (SQLException ex) {
            
           JOptionPane.showMessageDialog(null,ex,"PRINCE WHEEL",JOptionPane.WARNING_MESSAGE);
        }
        }else{
            JOptionPane.showMessageDialog(null,"Fill all the fields","PRINCE WHEEL",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnaddcarActionPerformed

    private void btnsearchaddcarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchaddcarActionPerformed
        // TODO add your handling code here:
        //validate search box
        if(!"".equals(txtcarno.getText())){
            
            try{
                con = DriverManager.getConnection(url,username,password);
            st = con.createStatement();
            String selectecar = "SELECT * FROM tbladmincar WHERE CARNO = ? ";
            pst = con.prepareStatement(selectecar);
            pst.setString(1,txtcarno.getText());
            rs = pst.executeQuery();
                    
            if(rs.next()){
                txtcarno.setText(rs.getString("CARNO"));
                txtcarprimeyears.setText(rs.getString("PRIMEYEARS"));
                txtcarcapacity.setText(rs.getString("CAPACITY"));
                txtinsurancecompany.setText(rs.getString("INSURENCECOMPANY"));
                jdbought.setDate(rs.getDate("DATEBOUGHT"));
                jdstatinsurance.setDate(rs.getDate("INSURENCASTART"));
                jdendinsurance.setDate(rs.getDate("INSURENCEEND"));
                cmbbranch.setSelectedItem(rs.getString("BRANCH"));
                cmbclass.setSelectedItem(rs.getString("CARCLASS"));
                cmbcarstatus.setSelectedItem(rs.getString("CURRENTSTATUS"));
                cmbcartype.setSelectedItem(rs.getString("CARTYPE"));
                
            }else{
                    JOptionPane.showMessageDialog(null,"Not found","PRINCE WHEEL",JOptionPane.WARNING_MESSAGE);
                    txtcarno.setText("");
                    txtcarprimeyears.setText("");
                    txtcarcapacity.setText("");
                    txtinsurancecompany.setText("");
                    jdbought.setDate(null);
                    jdstatinsurance.setDate(null);
                    jdendinsurance.setDate(null);
                      txtcarno.requestFocus();
                      
            }
                
            }
            catch(SQLException ex){
                JOptionPane.showMessageDialog(null,"Error"+ ex,"PRINCE WHEEL",JOptionPane.WARNING_MESSAGE);
            }
        }else{
             JOptionPane.showMessageDialog(null,"Enter car No","PRINCE WHEEL",JOptionPane.WARNING_MESSAGE);
            txtcarno.requestFocus(); 
        }
    }//GEN-LAST:event_btnsearchaddcarActionPerformed

    private void btndeletecarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeletecarActionPerformed
        // TODO add your handling code here:
        // update car details
     
            
    }//GEN-LAST:event_btndeletecarActionPerformed

    private void btnupdatecarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdatecarActionPerformed
        // TODO add your handling code here:
        //update car
        try{
            java.util.Date insstart,insend;
            java.sql.Date insuranceend,insurancestart;
            insstart =  jdstatinsurance.getDate();
            insend =  jdendinsurance.getDate();
            insurancestart = new java.sql.Date(insstart.getTime());
            insuranceend = new java.sql.Date(insend.getTime());
            
           con = DriverManager.getConnection(url,username,password);
            st = con.createStatement();
            String sqlupdatecar = "UPDATE tbladmincar set CURRENTSTATUS ='"+cmbcarstatus.getSelectedItem()+"',INSURENCECOMPANY='"+txtinsurancecompany.getText()+"',"
                    + "INSURENCASTART='"+insurancestart+"',INSURENCEEND='"+insuranceend+"',CARCLASS='"+cmbclass.getSelectedItem()+"'"
                    + ",BRANCH='"+cmbbranch.getSelectedItem()+"' WHERE CARNO = ?";
             pst = con.prepareStatement(sqlupdatecar);
            pst.setString(1,txtcarno.getText());
            pst.executeUpdate();
            
                JOptionPane.showMessageDialog(null,"Car updated","PRINCE WHEEL",JOptionPane.WARNING_MESSAGE);
         
            
        }catch(SQLException ex){
                         JOptionPane.showMessageDialog(null,"error" + ex,"PRINCE WHEEL",JOptionPane.WARNING_MESSAGE);

        }
    }//GEN-LAST:event_btnupdatecarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnaddcar;
    private javax.swing.JButton btndeletecar;
    private javax.swing.JButton btnholdcar;
    private javax.swing.JButton btnsearch;
    private javax.swing.JButton btnsearchaddcar;
    private javax.swing.JButton btnsearchreport;
    private javax.swing.JButton btnsearchstaffreport;
    private javax.swing.JButton btnupdatecar;
    private javax.swing.JComboBox<String> cmbbranch;
    private javax.swing.JComboBox<String> cmbcarstatus;
    private javax.swing.JComboBox<String> cmbcartype;
    private javax.swing.JComboBox<String> cmbcartypereport;
    private javax.swing.JComboBox<String> cmbclass;
    private javax.swing.JComboBox<String> cmbcounties;
    private javax.swing.JComboBox<String> cmbtype;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private com.toedter.calendar.JDateChooser jDateChooser4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private com.toedter.calendar.JDateChooser jdbought;
    private com.toedter.calendar.JDateChooser jdendinsurance;
    private com.toedter.calendar.JDateChooser jdstatinsurance;
    private javax.swing.JMenuItem jmaddcar;
    private javax.swing.JMenuItem jmaddstaff;
    private javax.swing.JMenuItem jmcarpricing;
    private javax.swing.JMenuItem jmcarreport;
    private javax.swing.JMenuItem jmdailyrequest;
    private javax.swing.JMenuItem jmlogout;
    private javax.swing.JMenuItem jmorgreport;
    private javax.swing.JMenuItem jmstaffaccount;
    private javax.swing.JMenuItem jmstaffreport;
    private javax.swing.JPanel jpaddcar;
    private javax.swing.JPanel jpaddstaff;
    private javax.swing.JPanel jpcarpricing;
    private javax.swing.JPanel jpcarreports;
    private javax.swing.JPanel jporgreport;
    private javax.swing.JPanel jpstaffaccount;
    private javax.swing.JPanel jpstaffreport;
    private javax.swing.JLabel lbcoution;
    private javax.swing.JLabel lbdiscount;
    private javax.swing.JLabel lbprice;
    private javax.swing.JLabel lbtype;
    private javax.swing.JTable tblcarreport;
    private javax.swing.JTable tblstaffreport;
    private javax.swing.JTextField txtcarcapacity;
    private javax.swing.JTextField txtcarno;
    private javax.swing.JTextField txtcarnoreport;
    private javax.swing.JTextField txtcarprimeyears;
    private javax.swing.JTextField txtinsurancecompany;
    // End of variables declaration//GEN-END:variables
}
