/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package princewheel;

import javax.swing.JOptionPane;

/**
 *
 * @author owner
 */
public class AdminHome extends javax.swing.JFrame {

    /**
     * Creates new form AdminHome
     */
    public AdminHome() {
        initComponents();
        hidecomponets();
    }
   final void hidecomponets(){
    jpstaffaccount.setVisible(false);
    jpaddcar.setVisible(false);
    jpcarpricing.setVisible(false);
    jpaddstaff.setVisible(false);
    jporgreport.setVisible(false);
    jpstaffreport.setVisible(false);
    jpcarreports.setVisible(false);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jpstaffaccount = new javax.swing.JPanel();
        jpcarpricing = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        cmbtype = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lbtype = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbdiscount = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lbcoution = new javax.swing.JLabel();
        lbprice = new javax.swing.JLabel();
        jpaddcar = new javax.swing.JPanel();
        jpaddstaff = new javax.swing.JPanel();
        jpcarreports = new javax.swing.JPanel();
        jpstaffreport = new javax.swing.JPanel();
        jporgreport = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmaddcar = new javax.swing.JMenuItem();
        jmcarpricing = new javax.swing.JMenuItem();
        jmlogout = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmcarreport = new javax.swing.JMenuItem();
        jmorgreport = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jmstaffreport = new javax.swing.JMenuItem();
        jmaddstaff = new javax.swing.JMenuItem();
        jmstaffaccount = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(1132, 537));
        jPanel1.setLayout(null);

        jpstaffaccount.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jpstaffaccountLayout = new javax.swing.GroupLayout(jpstaffaccount);
        jpstaffaccount.setLayout(jpstaffaccountLayout);
        jpstaffaccountLayout.setHorizontalGroup(
            jpstaffaccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );
        jpstaffaccountLayout.setVerticalGroup(
            jpstaffaccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );

        jPanel1.add(jpstaffaccount);
        jpstaffaccount.setBounds(370, 80, 390, 380);

        jpcarpricing.setBackground(new java.awt.Color(255, 255, 255));
        jpcarpricing.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Car pricing", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Wide Latin", 0, 12))); // NOI18N
        jpcarpricing.setLayout(null);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "New Price", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Wide Latin", 0, 11))); // NOI18N
        jPanel2.setLayout(null);

        jLabel1.setText("CAR TYPE :");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(10, 50, 60, 14);

        jLabel2.setText("COUTION :");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(10, 80, 54, 14);

        jLabel3.setText("LEASE PRICE :");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(10, 110, 70, 14);

        jLabel4.setText("DISCOUNT :");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(10, 150, 70, 14);

        jButton1.setBackground(new java.awt.Color(123, 193, 249));
        jButton1.setFont(new java.awt.Font("Wide Latin", 0, 11)); // NOI18N
        jButton1.setText("SAVE");
        jPanel2.add(jButton1);
        jButton1.setBounds(10, 281, 110, 40);

        jButton2.setBackground(new java.awt.Color(123, 193, 249));
        jButton2.setFont(new java.awt.Font("Wide Latin", 0, 11)); // NOI18N
        jButton2.setText("UPDATE");
        jPanel2.add(jButton2);
        jButton2.setBounds(130, 281, 130, 40);

        cmbtype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbtype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbtypeActionPerformed(evt);
            }
        });
        jPanel2.add(cmbtype);
        cmbtype.setBounds(110, 50, 130, 20);
        jPanel2.add(jTextField1);
        jTextField1.setBounds(110, 80, 130, 20);
        jPanel2.add(jTextField2);
        jTextField2.setBounds(110, 110, 130, 20);
        jPanel2.add(jTextField3);
        jTextField3.setBounds(110, 140, 130, 20);

        jpcarpricing.add(jPanel2);
        jPanel2.setBounds(6, 26, 280, 340);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Current Price", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Wide Latin", 0, 11))); // NOI18N
        jPanel3.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Wide Latin", 2, 11)); // NOI18N
        jLabel5.setText("CAR TYPE  :");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(20, 40, 130, 12);

        lbtype.setText("Type");
        jPanel3.add(lbtype);
        lbtype.setBounds(30, 70, 80, 14);

        jLabel7.setFont(new java.awt.Font("Wide Latin", 2, 11)); // NOI18N
        jLabel7.setText(" PRICE :");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(30, 110, 100, 12);

        lbdiscount.setText("Ksh .");
        jPanel3.add(lbdiscount);
        lbdiscount.setBounds(30, 210, 90, 14);

        jLabel9.setFont(new java.awt.Font("Wide Latin", 2, 11)); // NOI18N
        jLabel9.setText("DISCOUNT :");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(20, 180, 130, 12);

        jLabel10.setFont(new java.awt.Font("Wide Latin", 2, 11)); // NOI18N
        jLabel10.setText("COUTION :");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(20, 240, 120, 12);

        lbcoution.setText("Ksh .");
        jPanel3.add(lbcoution);
        lbcoution.setBounds(30, 270, 100, 14);

        lbprice.setText("Ksh .");
        jPanel3.add(lbprice);
        lbprice.setBounds(30, 140, 80, 14);

        jpcarpricing.add(jPanel3);
        jPanel3.setBounds(300, 30, 180, 330);

        jPanel1.add(jpcarpricing);
        jpcarpricing.setBounds(310, 80, 510, 380);

        jpaddcar.setBackground(new java.awt.Color(255, 255, 204));

        javax.swing.GroupLayout jpaddcarLayout = new javax.swing.GroupLayout(jpaddcar);
        jpaddcar.setLayout(jpaddcarLayout);
        jpaddcarLayout.setHorizontalGroup(
            jpaddcarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );
        jpaddcarLayout.setVerticalGroup(
            jpaddcarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );

        jPanel1.add(jpaddcar);
        jpaddcar.setBounds(200, 80, 750, 430);

        javax.swing.GroupLayout jpaddstaffLayout = new javax.swing.GroupLayout(jpaddstaff);
        jpaddstaff.setLayout(jpaddstaffLayout);
        jpaddstaffLayout.setHorizontalGroup(
            jpaddstaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 870, Short.MAX_VALUE)
        );
        jpaddstaffLayout.setVerticalGroup(
            jpaddstaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );

        jPanel1.add(jpaddstaff);
        jpaddstaff.setBounds(140, 80, 870, 430);

        jpcarreports.setBackground(new java.awt.Color(153, 255, 153));

        javax.swing.GroupLayout jpcarreportsLayout = new javax.swing.GroupLayout(jpcarreports);
        jpcarreports.setLayout(jpcarreportsLayout);
        jpcarreportsLayout.setHorizontalGroup(
            jpcarreportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 940, Short.MAX_VALUE)
        );
        jpcarreportsLayout.setVerticalGroup(
            jpcarreportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );

        jPanel1.add(jpcarreports);
        jpcarreports.setBounds(90, 80, 940, 430);

        jpstaffreport.setBackground(new java.awt.Color(255, 204, 51));

        javax.swing.GroupLayout jpstaffreportLayout = new javax.swing.GroupLayout(jpstaffreport);
        jpstaffreport.setLayout(jpstaffreportLayout);
        jpstaffreportLayout.setHorizontalGroup(
            jpstaffreportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1010, Short.MAX_VALUE)
        );
        jpstaffreportLayout.setVerticalGroup(
            jpstaffreportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );

        jPanel1.add(jpstaffreport);
        jpstaffreport.setBounds(40, 80, 1010, 430);

        jporgreport.setBackground(new java.awt.Color(255, 153, 153));

        javax.swing.GroupLayout jporgreportLayout = new javax.swing.GroupLayout(jporgreport);
        jporgreport.setLayout(jporgreportLayout);
        jporgreportLayout.setHorizontalGroup(
            jporgreportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
        );
        jporgreportLayout.setVerticalGroup(
            jporgreportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );

        jPanel1.add(jporgreport);
        jporgreport.setBounds(30, 80, 1080, 430);

        jMenu1.setText("Activity");

        jmaddcar.setText("Add Car");
        jmaddcar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmaddcarActionPerformed(evt);
            }
        });
        jMenu1.add(jmaddcar);

        jmcarpricing.setText("Car Priicing");
        jmcarpricing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmcarpricingActionPerformed(evt);
            }
        });
        jMenu1.add(jmcarpricing);

        jmlogout.setText("Logout");
        jmlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmlogoutActionPerformed(evt);
            }
        });
        jMenu1.add(jmlogout);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Reports");

        jmcarreport.setText("Car Reports");
        jmcarreport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmcarreportActionPerformed(evt);
            }
        });
        jMenu2.add(jmcarreport);

        jmorgreport.setText("Org Report");
        jmorgreport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmorgreportActionPerformed(evt);
            }
        });
        jMenu2.add(jmorgreport);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Staff");

        jmstaffreport.setText("Staff Reports");
        jmstaffreport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmstaffreportActionPerformed(evt);
            }
        });
        jMenu3.add(jmstaffreport);

        jmaddstaff.setText("Add Staff");
        jmaddstaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmaddstaffActionPerformed(evt);
            }
        });
        jMenu3.add(jmaddstaff);

        jmstaffaccount.setText("Staff Accounts");
        jmstaffaccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmstaffaccountActionPerformed(evt);
            }
        });
        jMenu3.add(jmstaffaccount);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1151, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jmlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmlogoutActionPerformed
        // TODO add your handling code here:
        int action = JOptionPane.showConfirmDialog(null, "Are you sure to exit ?","PRINCE WHEEL",JOptionPane.YES_NO_OPTION);
        switch (action) {
            case JOptionPane.YES_OPTION:
                this.dispose();
                new Loader().setVisible(true);
                break;
            case JOptionPane.NO_OPTION:
                JOptionPane.showMessageDialog(null,"Still loged in ","PRINCE WHEEL",JOptionPane.INFORMATION_MESSAGE);
                break;
            default:
                JOptionPane.showMessageDialog(null,"Error occoured contact admin ","PRINCE WHEEL",JOptionPane.ERROR);
                break;
        }
    }//GEN-LAST:event_jmlogoutActionPerformed

    private void jmaddcarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmaddcarActionPerformed
        // TODO add your handling code here:
    jpstaffaccount.setVisible(false);
    
    jpcarpricing.setVisible(false);
    jpaddstaff.setVisible(false);
    jporgreport.setVisible(false);
    jpstaffreport.setVisible(false);
    jpcarreports.setVisible(false);
    jpaddcar.setVisible(true);
    }//GEN-LAST:event_jmaddcarActionPerformed

    private void jmcarpricingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmcarpricingActionPerformed
        // TODO add your handling code here:
          jpstaffaccount.setVisible(false);
    jpaddstaff.setVisible(false);
    jporgreport.setVisible(false);
    jpstaffreport.setVisible(false);
    jpcarreports.setVisible(false);
    jpaddcar.setVisible(false);
    jpcarpricing.setVisible(true);
    }//GEN-LAST:event_jmcarpricingActionPerformed

    private void jmaddstaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmaddstaffActionPerformed
        // TODO add your handling code here:
         jpstaffaccount.setVisible(false);
    
    jporgreport.setVisible(false);
    jpstaffreport.setVisible(false);
    jpcarreports.setVisible(false);
    jpaddcar.setVisible(false);
    jpcarpricing.setVisible(false);
    jpaddstaff.setVisible(true);
    }//GEN-LAST:event_jmaddstaffActionPerformed

    private void jmcarreportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmcarreportActionPerformed
        // TODO add your handling code here:
          jpstaffaccount.setVisible(false);
    jpaddstaff.setVisible(false);
    jporgreport.setVisible(false);
    jpstaffreport.setVisible(false);
    jpaddcar.setVisible(false);
    jpcarpricing.setVisible(false);
    jpcarreports.setVisible(true);
    }//GEN-LAST:event_jmcarreportActionPerformed

    private void jmorgreportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmorgreportActionPerformed
        // TODO add your handling code here:
            jpstaffaccount.setVisible(false);
    jpaddstaff.setVisible(false);
    jpstaffreport.setVisible(false);
    jpaddcar.setVisible(false);
    jpcarpricing.setVisible(false);
    jpcarreports.setVisible(false);
    jporgreport.setVisible(true);
    }//GEN-LAST:event_jmorgreportActionPerformed

    private void jmstaffreportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmstaffreportActionPerformed
        // TODO add your handling code here:
              jpstaffaccount.setVisible(false);
    jpaddstaff.setVisible(false);  
    jpaddcar.setVisible(false);
    jpcarpricing.setVisible(false);
    jpcarreports.setVisible(false);
    jporgreport.setVisible(false);
    jpstaffreport.setVisible(true);
    }//GEN-LAST:event_jmstaffreportActionPerformed

    private void jmstaffaccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmstaffaccountActionPerformed
        // TODO add your handling code here:
              
    jpaddstaff.setVisible(false);  
    jpaddcar.setVisible(false);
    jpcarpricing.setVisible(false);
    jpcarreports.setVisible(false);
    jporgreport.setVisible(false);
    jpstaffreport.setVisible(false);
    jpstaffaccount.setVisible(true);
    }//GEN-LAST:event_jmstaffaccountActionPerformed

    private void cmbtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbtypeActionPerformed
        // TODO add your handling code here:
        int selecteditem = cmbtype.getSelectedIndex();
        if(selecteditem == 0){
            String type = cmbtype.getItemAt(0);
        lbtype.setText(type);
        
        }else if(selecteditem == 1){
         String type = cmbtype.getItemAt(1);
        lbtype.setText(type);
        }
        else if(selecteditem == 2){
         String type = cmbtype.getItemAt(2);
        lbtype.setText(type);
        }
        else if(selecteditem == 3){
         String type = cmbtype.getItemAt(3);
        lbtype.setText(type);
        }
        
        else{
        JOptionPane.showMessageDialog(null, "error");
        }
    }//GEN-LAST:event_cmbtypeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbtype;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JMenuItem jmaddcar;
    private javax.swing.JMenuItem jmaddstaff;
    private javax.swing.JMenuItem jmcarpricing;
    private javax.swing.JMenuItem jmcarreport;
    private javax.swing.JMenuItem jmlogout;
    private javax.swing.JMenuItem jmorgreport;
    private javax.swing.JMenuItem jmstaffaccount;
    private javax.swing.JMenuItem jmstaffreport;
    private javax.swing.JPanel jpaddcar;
    private javax.swing.JPanel jpaddstaff;
    private javax.swing.JPanel jpcarpricing;
    private javax.swing.JPanel jpcarreports;
    private javax.swing.JPanel jporgreport;
    private javax.swing.JPanel jpstaffaccount;
    private javax.swing.JPanel jpstaffreport;
    private javax.swing.JLabel lbcoution;
    private javax.swing.JLabel lbdiscount;
    private javax.swing.JLabel lbprice;
    private javax.swing.JLabel lbtype;
    // End of variables declaration//GEN-END:variables
}
