/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package princewheel;

/**
 *
 * @author owner
 */
public class AgentHome extends javax.swing.JFrame {

    /**
     * Creates new form AgentHome
     */
    public AgentHome() {
        initComponents();
        hidepanels();
    }
    void hidepanels(){
    jprequest.setVisible(false);
    jpclearlease.setVisible(false);
    jpleasenow.setVisible(false);
    jpcarreport.setVisible(false);
    jpclientreport.setVisible(false);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jpleasenow = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jprequest = new javax.swing.JPanel();
        jpclearlease = new javax.swing.JPanel();
        jpclientreport = new javax.swing.JPanel();
        jpcarreport = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmleasenow = new javax.swing.JMenuItem();
        jmclearlease = new javax.swing.JMenuItem();
        jmrequest = new javax.swing.JMenuItem();
        jmlogout = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmclientreport = new javax.swing.JMenuItem();
        jmcarreport = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1152, 541));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(248, 248, 248));
        jPanel1.setLayout(null);

        jpleasenow.setBackground(new java.awt.Color(153, 204, 255));
        jpleasenow.setLayout(null);

        jTable1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jpleasenow.add(jScrollPane1);
        jScrollPane1.setBounds(30, 340, 1020, 140);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(null);

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel3.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Wide Latin", 0, 12)); // NOI18N
        jLabel1.setText("CLIENT DETAILS");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(40, 10, 220, 20);

        jPanel2.add(jPanel3);
        jPanel3.setBounds(10, 10, 340, 300);

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel4.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Wide Latin", 0, 12)); // NOI18N
        jLabel2.setText("CAR DETAILS");
        jPanel4.add(jLabel2);
        jLabel2.setBounds(84, 13, 230, 20);

        jPanel2.add(jPanel4);
        jPanel4.setBounds(380, 10, 320, 300);

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel5.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Wide Latin", 0, 12)); // NOI18N
        jLabel3.setText("PRICE ALLOWED");
        jPanel5.add(jLabel3);
        jLabel3.setBounds(30, 20, 210, 13);

        jPanel2.add(jPanel5);
        jPanel5.setBounds(740, 10, 300, 300);

        jpleasenow.add(jPanel2);
        jPanel2.setBounds(10, 10, 1060, 320);

        jPanel1.add(jpleasenow);
        jpleasenow.setBounds(10, 10, 1090, 490);

        jprequest.setBackground(new java.awt.Color(255, 204, 204));

        javax.swing.GroupLayout jprequestLayout = new javax.swing.GroupLayout(jprequest);
        jprequest.setLayout(jprequestLayout);
        jprequestLayout.setHorizontalGroup(
            jprequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1040, Short.MAX_VALUE)
        );
        jprequestLayout.setVerticalGroup(
            jprequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        jPanel1.add(jprequest);
        jprequest.setBounds(30, 20, 1040, 450);

        jpclearlease.setBackground(new java.awt.Color(153, 255, 102));

        javax.swing.GroupLayout jpclearleaseLayout = new javax.swing.GroupLayout(jpclearlease);
        jpclearlease.setLayout(jpclearleaseLayout);
        jpclearleaseLayout.setHorizontalGroup(
            jpclearleaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1060, Short.MAX_VALUE)
        );
        jpclearleaseLayout.setVerticalGroup(
            jpclearleaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );

        jPanel1.add(jpclearlease);
        jpclearlease.setBounds(20, 30, 1060, 440);

        javax.swing.GroupLayout jpclientreportLayout = new javax.swing.GroupLayout(jpclientreport);
        jpclientreport.setLayout(jpclientreportLayout);
        jpclientreportLayout.setHorizontalGroup(
            jpclientreportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jpclientreportLayout.setVerticalGroup(
            jpclientreportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );

        jPanel1.add(jpclientreport);
        jpclientreport.setBounds(190, 20, 800, 470);

        javax.swing.GroupLayout jpcarreportLayout = new javax.swing.GroupLayout(jpcarreport);
        jpcarreport.setLayout(jpcarreportLayout);
        jpcarreportLayout.setHorizontalGroup(
            jpcarreportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1020, Short.MAX_VALUE)
        );
        jpcarreportLayout.setVerticalGroup(
            jpcarreportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        jPanel1.add(jpcarreport);
        jpcarreport.setBounds(40, 20, 1020, 480);

        jMenu1.setText("Lease Dashboard");

        jmleasenow.setText("Lease Now");
        jmleasenow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmleasenowActionPerformed(evt);
            }
        });
        jMenu1.add(jmleasenow);

        jmclearlease.setText("Clear Lease");
        jmclearlease.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmclearleaseActionPerformed(evt);
            }
        });
        jMenu1.add(jmclearlease);

        jmrequest.setText("Make Request");
        jmrequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmrequestActionPerformed(evt);
            }
        });
        jMenu1.add(jmrequest);

        jmlogout.setText("Logout");
        jmlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmlogoutActionPerformed(evt);
            }
        });
        jMenu1.add(jmlogout);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Reports");

        jmclientreport.setText("Client Reports");
        jmclientreport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmclientreportActionPerformed(evt);
            }
        });
        jMenu2.add(jmclientreport);

        jmcarreport.setText("Car Reports");
        jmcarreport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmcarreportActionPerformed(evt);
            }
        });
        jMenu2.add(jmcarreport);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1152, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jmleasenowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmleasenowActionPerformed
        // TODO add your handling code here:
        jpleasenow.setVisible(true);
          jprequest.setVisible(true);
    jpclearlease.setVisible(false);
    
    }//GEN-LAST:event_jmleasenowActionPerformed

    private void jmlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmlogoutActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Loader().setVisible(true);
    }//GEN-LAST:event_jmlogoutActionPerformed

    private void jmrequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmrequestActionPerformed
        // TODO add your handling code here:
        jprequest.setVisible(true);
    jpclearlease.setVisible(false);
    jpleasenow.setVisible(false);
    jpcarreport.setVisible(false);
    jpclientreport.setVisible(false);
    }//GEN-LAST:event_jmrequestActionPerformed

    private void jmclearleaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmclearleaseActionPerformed
        // TODO add your handling code here:
        jpclearlease.setVisible(true);
        jprequest.setVisible(false);
        jpcarreport.setVisible(false);
    jpclientreport.setVisible(false);
    
    jpleasenow.setVisible(false);
    }//GEN-LAST:event_jmclearleaseActionPerformed

    private void jmclientreportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmclientreportActionPerformed
        // TODO add your handling code here:
        jpclientreport.setVisible(true);
        jprequest.setVisible(false);
    jpclearlease.setVisible(false);
    jpleasenow.setVisible(false);
    jpcarreport.setVisible(false);
    
    }//GEN-LAST:event_jmclientreportActionPerformed

    private void jmcarreportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmcarreportActionPerformed
        // TODO add your handling code here:
        jpcarreport.setVisible(true);
        jpclientreport.setVisible(false);
        jprequest.setVisible(false);
    jpclearlease.setVisible(false);
    jpleasenow.setVisible(false);
    
    }//GEN-LAST:event_jmcarreportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgentHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgentHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgentHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgentHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgentHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JMenuItem jmcarreport;
    private javax.swing.JMenuItem jmclearlease;
    private javax.swing.JMenuItem jmclientreport;
    private javax.swing.JMenuItem jmleasenow;
    private javax.swing.JMenuItem jmlogout;
    private javax.swing.JMenuItem jmrequest;
    private javax.swing.JPanel jpcarreport;
    private javax.swing.JPanel jpclearlease;
    private javax.swing.JPanel jpclientreport;
    private javax.swing.JPanel jpleasenow;
    private javax.swing.JPanel jprequest;
    // End of variables declaration//GEN-END:variables
}
