/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package princewheel;

import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.Timer;

/**
 *
 * @author owner
 */
public class Loader extends javax.swing.JFrame {

    /**
     * Creates new form Loader
     */
    public Loader() {
        initComponents();
        loadimages();
        showdate();
        showtime();
    }
        final void loadimages(){
     
        ImageIcon img1,img2,img3,img4;
         img1 = new ImageIcon("images/bmv.png");
         img2 = new ImageIcon("images/hummer.png");
         img3 = new ImageIcon("images/keys.png");
         img4 = new ImageIcon("images/wheel2.png");
        lbimage1.setIcon(img1);
        lbimage2.setIcon(img2);
        lbimage3.setIcon(img3);
        lbimage4.setIcon(img4);
        
}
        final void showdate(){
        Date date = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
        lbdate.setText("Date :" + sdf.format(date));
        
        }
        final void showtime(){
        new Timer (0, (ActionEvent ae) -> {
            Date date = new Date();
            SimpleDateFormat sdf = new SimpleDateFormat("hh-mm-ss a");
            lbtime.setText("Time :" + sdf.format(date));
        }){}.start();
        
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbdate = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnengineer = new javax.swing.JButton();
        btncreateacount = new javax.swing.JButton();
        btnagent = new javax.swing.JButton();
        btnadmin = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        lbimage1 = new javax.swing.JLabel();
        lbimage4 = new javax.swing.JLabel();
        lbimage2 = new javax.swing.JLabel();
        lbimage3 = new javax.swing.JLabel();
        lbtime = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PRINCE WHEEL");
        setResizable(false);

        jPanel1.setMinimumSize(new java.awt.Dimension(839, 445));
        jPanel1.setName(""); // NOI18N
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Wide Latin", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Prince wheel ");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jLabel1.setOpaque(true);

        lbdate.setBackground(new java.awt.Color(255, 255, 255));
        lbdate.setFont(new java.awt.Font("Wide Latin", 0, 18)); // NOI18N
        lbdate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbdate.setText("Date :");
        lbdate.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lbdate.setOpaque(true);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addComponent(lbdate, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbdate, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(30, 30, 780, 74);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(null);

        btnengineer.setBackground(new java.awt.Color(123, 193, 249));
        btnengineer.setFont(new java.awt.Font("Wide Latin", 0, 14)); // NOI18N
        btnengineer.setText("ENGINEER");
        btnengineer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel3.add(btnengineer);
        btnengineer.setBounds(320, 20, 190, 50);

        btncreateacount.setBackground(new java.awt.Color(123, 193, 249));
        btncreateacount.setFont(new java.awt.Font("Wide Latin", 0, 10)); // NOI18N
        btncreateacount.setText("CREATE ACCOUNT");
        btncreateacount.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btncreateacount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncreateacountActionPerformed(evt);
            }
        });
        jPanel3.add(btncreateacount);
        btncreateacount.setBounds(550, 30, 220, 50);

        btnagent.setBackground(new java.awt.Color(123, 193, 249));
        btnagent.setFont(new java.awt.Font("Wide Latin", 0, 14)); // NOI18N
        btnagent.setText("AGENT");
        btnagent.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnagent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagentActionPerformed(evt);
            }
        });
        jPanel3.add(btnagent);
        btnagent.setBounds(170, 20, 140, 50);

        btnadmin.setBackground(new java.awt.Color(123, 193, 249));
        btnadmin.setFont(new java.awt.Font("Wide Latin", 0, 14)); // NOI18N
        btnadmin.setText("ADMIN");
        btnadmin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnadminActionPerformed(evt);
            }
        });
        jPanel3.add(btnadmin);
        btnadmin.setBounds(10, 20, 150, 50);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(30, 110, 780, 90);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setLayout(null);

        lbimage1.setOpaque(true);
        jPanel4.add(lbimage1);
        lbimage1.setBounds(10, 20, 150, 140);

        lbimage4.setOpaque(true);
        jPanel4.add(lbimage4);
        lbimage4.setBounds(570, 20, 150, 140);

        lbimage2.setOpaque(true);
        jPanel4.add(lbimage2);
        lbimage2.setBounds(190, 20, 160, 140);

        lbimage3.setOpaque(true);
        jPanel4.add(lbimage3);
        lbimage3.setBounds(380, 20, 150, 140);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(30, 220, 780, 170);

        lbtime.setBackground(new java.awt.Color(255, 255, 255));
        lbtime.setFont(new java.awt.Font("Wide Latin", 0, 18)); // NOI18N
        lbtime.setText("Time :");
        lbtime.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lbtime.setOpaque(true);
        jPanel1.add(lbtime);
        lbtime.setBounds(270, 400, 350, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnagentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagentActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new AgentHome().setVisible(true);
    }//GEN-LAST:event_btnagentActionPerformed

    private void btncreateacountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncreateacountActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new CreateAccount().setVisible(true);
    }//GEN-LAST:event_btncreateacountActionPerformed

    private void btnadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnadminActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new AdminHome().setVisible(true);
    }//GEN-LAST:event_btnadminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Loader.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Loader.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Loader.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Loader.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Loader().setVisible(true);
            }
        });
    }
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadmin;
    private javax.swing.JButton btnagent;
    private javax.swing.JButton btncreateacount;
    private javax.swing.JButton btnengineer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lbdate;
    private javax.swing.JLabel lbimage1;
    private javax.swing.JLabel lbimage2;
    private javax.swing.JLabel lbimage3;
    private javax.swing.JLabel lbimage4;
    private javax.swing.JLabel lbtime;
    // End of variables declaration//GEN-END:variables
}

